version: '3.9'
services:
  node:
    restart: always
    image: ma_super_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_PORT=3306
      - DATABASE_PASSWORD=azerty
      - DATABASE_NAME=ma_super_app
      - DATABASE_USERNAME=root
      - DATABASE_HOST=db
    ports:
      - 80:3000
    networks:
      - mysql-network
  db:
    image: mysql:5.7-debian
    environment:
      MYSQL_ROOT_PASSWORD: azerty
      MYSQL_DATABASE: ma_super_app
    expose:
      - 3306
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge
